# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts import simulation_pb2 as contracts_dot_simulation__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contracts/simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnvironmentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRun = channel.unary_unary(
                '/simulation.v1.Environment/StartRun',
                request_serializer=contracts_dot_simulation__pb2.StartRequest.SerializeToString,
                response_deserializer=contracts_dot_simulation__pb2.RunState.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/simulation.v1.Environment/Observe',
                request_serializer=contracts_dot_simulation__pb2.RunRequest.SerializeToString,
                response_deserializer=contracts_dot_simulation__pb2.Observation.FromString,
                _registered_method=True)
        self.ApplyAction = channel.unary_unary(
                '/simulation.v1.Environment/ApplyAction',
                request_serializer=contracts_dot_simulation__pb2.ActionRequest.SerializeToString,
                response_deserializer=contracts_dot_simulation__pb2.TurnEvent.FromString,
                _registered_method=True)
        self.GetRunState = channel.unary_unary(
                '/simulation.v1.Environment/GetRunState',
                request_serializer=contracts_dot_simulation__pb2.RunRequest.SerializeToString,
                response_deserializer=contracts_dot_simulation__pb2.RunState.FromString,
                _registered_method=True)
        self.GetTurnEvents = channel.unary_unary(
                '/simulation.v1.Environment/GetTurnEvents',
                request_serializer=contracts_dot_simulation__pb2.EventsRequest.SerializeToString,
                response_deserializer=contracts_dot_simulation__pb2.Events.FromString,
                _registered_method=True)
        self.EndRun = channel.unary_unary(
                '/simulation.v1.Environment/EndRun',
                request_serializer=contracts_dot_simulation__pb2.RunRequest.SerializeToString,
                response_deserializer=contracts_dot_simulation__pb2.RunState.FromString,
                _registered_method=True)


class EnvironmentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTurnEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=contracts_dot_simulation__pb2.StartRequest.FromString,
                    response_serializer=contracts_dot_simulation__pb2.RunState.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=contracts_dot_simulation__pb2.RunRequest.FromString,
                    response_serializer=contracts_dot_simulation__pb2.Observation.SerializeToString,
            ),
            'ApplyAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyAction,
                    request_deserializer=contracts_dot_simulation__pb2.ActionRequest.FromString,
                    response_serializer=contracts_dot_simulation__pb2.TurnEvent.SerializeToString,
            ),
            'GetRunState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunState,
                    request_deserializer=contracts_dot_simulation__pb2.RunRequest.FromString,
                    response_serializer=contracts_dot_simulation__pb2.RunState.SerializeToString,
            ),
            'GetTurnEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTurnEvents,
                    request_deserializer=contracts_dot_simulation__pb2.EventsRequest.FromString,
                    response_serializer=contracts_dot_simulation__pb2.Events.SerializeToString,
            ),
            'EndRun': grpc.unary_unary_rpc_method_handler(
                    servicer.EndRun,
                    request_deserializer=contracts_dot_simulation__pb2.RunRequest.FromString,
                    response_serializer=contracts_dot_simulation__pb2.RunState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulation.v1.Environment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simulation.v1.Environment', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Environment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulation.v1.Environment/StartRun',
            contracts_dot_simulation__pb2.StartRequest.SerializeToString,
            contracts_dot_simulation__pb2.RunState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulation.v1.Environment/Observe',
            contracts_dot_simulation__pb2.RunRequest.SerializeToString,
            contracts_dot_simulation__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulation.v1.Environment/ApplyAction',
            contracts_dot_simulation__pb2.ActionRequest.SerializeToString,
            contracts_dot_simulation__pb2.TurnEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulation.v1.Environment/GetRunState',
            contracts_dot_simulation__pb2.RunRequest.SerializeToString,
            contracts_dot_simulation__pb2.RunState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTurnEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulation.v1.Environment/GetTurnEvents',
            contracts_dot_simulation__pb2.EventsRequest.SerializeToString,
            contracts_dot_simulation__pb2.Events.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulation.v1.Environment/EndRun',
            contracts_dot_simulation__pb2.RunRequest.SerializeToString,
            contracts_dot_simulation__pb2.RunState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
